jarvis:
  threshold: 0.5
  cooldown_seconds: 2.5
  volume_multiplier: 1.0

integrations:
  warp:
    path: "${WARP_PATH}"

wakewords:
  programar:
     action: warp
     commands:
       - 'cd ${PROJECT_PATH}'
       - 'code .'
       - 'gemini'
       
  fechar_tudo:
    action: system
    risk_level: "dangerous"
    commands:
      - 'echo "Simulating close all..."'
